### ISSUE TITLE
Broken link in mobile README file

### ISSUE THREAD

**Issue by HassanBahati** [airqo-platform/AirQo-frontend#1010]
**What were you trying to achieve?**
The link to the [contributing guide](https://github.com/airqo-platform/AirQo-frontend/blob/staging/CONTRIBUTING.md) under the [README.md](https://github.com/airqo-platform/AirQo-frontend/blob/staging/mobile/README.md) results in a 404 not found page.
![Screenshot from 2023-01-06 16-52-13](https://user-images.githubusercontent.com/65954740/211026910-834a28a8-2470-4aee-98be-e10237f76feb.png)

**What are the expected results?**
Expected to route to [CONTRIBUTING.md](https://github.com/airqo-platform/AirQo-frontend/blob/staging/CONTRIBUTING.md)

**What are the received results?**
![Screenshot from 2023-01-06 16-56-09](https://user-images.githubusercontent.com/65954740/211026416-4f5cf151-9d06-425d-9e1e-06dcab3d730b.png)

**What are the steps to reproduce the issue?**
1. go to [/mobile/README.md](https://github.com/airqo-platform/AirQo-frontend/blob/staging/mobile/README.md) 
2. click the `here` link under the section `For Contributors`

**In what environment did you encounter the issue?**
 - OS: Ubuntu 
 - Version 20.04

**Comment by HassanBahati** [comment]
cc @123MwanjeMike @NoahNsimbe

**Comment by 123MwanjeMike** [comment]
Thanks @HassanBahati for raising this.
Let me add the necessary metadata to this PR
cc @NoahNsimbe

**Comment by NoahNsimbe** [comment]
Thanks @HassanBahati and @123MwanjeMike

**Comment by 123MwanjeMike** [comment]
Solved by #1011
