### ISSUE TITLE
[Analytics] Download option for maps missing

### ISSUE THREAD

**Issue by Baalmart** [airqo-platform/AirQo-frontend#103]
- What were you trying to achieve?
Download options for the map in Analytics
- What are the expected results?
See the options for downloading
- What are the received results?
Options do not exist
- What are the steps to reproduce the issue?
Just run latest analytics in `staging` branch
- In what environment did you encounter the issue?
> Google chrome browser.
> Node version v12.15.0

**Comment by ja-odur** [comment]
Resolved
