### ISSUE TITLE
[Analytics] No input validation on reset password

### ISSUE THREAD

**Issue by Baalmart** [airqo-platform/AirQo-frontend#107]
- What were you trying to achieve?
Reset the password
- What are the expected results?
Password reset
- What are the received results?
No response to user after incorrect input
- What are the steps to reproduce the issue?
Visit the **Analytics staging link:** http://34.78.78.202:31103/
And then visit **Login** >> **Forgot Password** and then check email to click on link.
The link will lead you to the reset password page where you will enter your new password.
Try entering a password which does **NOT** meet the requirements (less than 6 letters, no uppercase and no number in it)
- In what environment did you encounter the issue?
Chrome browser: Version 83.0.4103.116 (Official Build) (64-bit)

**Comment by ja-odur** [comment]
Tested this, the validations were added
