### ISSUE TITLE
[Analytics] No confirmation message on Forgot Password

### ISSUE THREAD

**Issue by Baalmart** [airqo-platform/AirQo-frontend#108]
- What were you trying to achieve?
Send an email for resetting my password
- What are the expected results?
Confirmation message that the email has been sent. 
- What are the received results?
There is no confirmation message for the sent email after submitting an email address
- What are the steps to reproduce the issue?
Head over to the **Analytics staging link:** http://34.78.78.202:31103/
And then Login >>> Forgot Password >>> enter email address and then SUBMIT
- In what environment did you encounter the issue?
Chrome browser Version 83.0.4103.116 (Official Build) (64-bit)

**Comment by ja-odur** [comment]
This has been resolved
