### ISSUE TITLE
technical debt in netmanager

### ISSUE THREAD

**Issue by Baalmart** [airqo-platform/AirQo-frontend#115]
1. Usage of axios library:
```
const params = {
	articleNumber: this.articleNumber,
	mode: 'bestseller',
};

const response = await axios.$get('/api/slider', { params });
```

2. code reusability: I noticed similar code else where (netmanager/src/views/components/DataDisplay/DeviceView.js), could we explore code reusability?

Gotten from[ this PR](https://github.com/airqo-platform/AirQo-frontend/pull/106)

**Comment by ja-odur** [comment]
THis is still a valid issue @Baalmart @lilly-muyama

**Comment by Baalmart** [comment]
> Is this still a valid issue @Baalmart @lilly-muyama

I am not sure, I gather a lot of refactoring has happened ever since then. And still ongoing.....
Closing now.......
