### ISSUE TITLE
Analytics search feature

### ISSUE THREAD

**Issue by noahnsimbe** [airqo-platform/AirQo-frontend#1217]
**Is your feature request related to a problem? Please describe.**
I am having trouble locating the search feature on the legacy analytics platform

**Describe the solution you'd like**
I want a user to be able to easily locate the feature. Make it more visible. 

**Describe alternatives you've considered**
Substitute it with a search bar.

**Additional context**
None.

**Comment by MartinKalema** [comment]
Was this issue solved?
