### ISSUE TITLE
[Location Registry] Never ending progress button

### ISSUE THREAD

**Issue by Baalmart** [airqo-platform/AirQo-frontend#127]
- What were you trying to achieve?
View the locations while while running localhost
- What are the expected results?
When locations do not exist, the Loading/Progress indicators should not be there. Just return "no locations exist" is what I expect.
- What are the received results?
The progress/loading button just continues indefinitely
![image](https://user-images.githubusercontent.com/1590213/91972883-fea3b000-ed23-11ea-8e4a-20f95ab2b56c.png)

- What are the steps to reproduce the issue?
```
cd netmanager
npm install
```
> For MAC users:

`npm run dev-mac`
> For Windows Users:

`npm run dev-pc`

- In what environment did you encounter the issue?
Google Chrome Version 84.0.4147.135 (Official Build) (64-bit)

**Comment by ja-odur** [comment]
The tables were fully reimplemented using material-table, so this is no longer an issue.
