### ISSUE TITLE
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by Baalmart** [airqo-platform/AirQo-frontend#133]
- What were you trying to achieve?
running npm run build
- What are the expected results?
successful build
- What are the received results?
![image](https://user-images.githubusercontent.com/1590213/92481488-18933600-f1ef-11ea-9665-1d83213e3e28.png)

- What are the steps to reproduce the issue?
```
cd AirQo-frontend/netmanager
npm install
npm run build
```
- In what environment did you encounter the issue?
node 12.16.1

**Comment by Baalmart** [comment]
resolved by @ja-odur cc: @danielogen

**Comment by danielogen** [comment]
Great work...I haven't tried with rocker though but I think all should be fine. Thanks again!
