### ISSUE TITLE
View all exceedances button not working

### ISSUE THREAD

**Issue by Codebmk** [airqo-platform/AirQo-frontend#1379]
![image](https://github.com/airqo-platform/AirQo-frontend/assets/46527380/ccd4c601-4e61-4693-a148-020257e68795)

**Comment by danielmarv** [comment]
It works but I think it will need a loader because it takes time on loading

**Comment by danielmarv** [comment]
My PC has crashed but I will start on that in the evening because the repair will be done

**Comment by danielmarv** [comment]
solved!!!
