### ISSUE TITLE
[Netmanager] Long delay in the loading of dashboard customised charts

### ISSUE THREAD

**Issue by Baalmart** [airqo-platform/AirQo-frontend#151]
- What were you trying to achieve?
View the customised charts in the Dashboard after login

- What are the expected results?
Quick load up of the customised charts

- What are the received results?
The customiosable charts do not load up, the page is short - only loads up cxceedances , mean daily graph and the map.
![image](https://user-images.githubusercontent.com/1590213/94267360-21506f80-ff44-11ea-97b1-0337ed07c9ad.png)

- What are the steps to reproduce the issue?
```
cd AirQo-frontend/netmanager
npm install
```

> for MAC

`npm run stage-mac` OR `npm run prod-mac`

> for Windows

`npm run stage-pc` OR `npm run stage-pc`

- In what environment did you encounter the issue?
node 12.18.1

**Comment by ja-odur** [comment]
This was resolved too
