### ISSUE TITLE
Spelling Errors and Typos on https://wiki.airqo.net/#/calibration/airqalibrate

### ISSUE THREAD

**Issue by moadams847** [airqo-platform/AirQo-frontend#1583]
I've encountered a couple of spelling errors on the https://wiki.airqo.net/#/calibration/airqalibrate page of the website. The word 'show' is currently misspelled, and it should be corrected to 'should.' Additionally, the word 'will' is also misspelled and should be corrected to 'with.' These minor typos need to be addressed to enhance website quality and user experience.

**Comment by ankur-dahiya** [comment]
please assign me this issue as i am already working on it

**Comment by ankur-dahiya** [comment]
please merge this pull request with appropriate tags
