### ISSUE TITLE
Mobile app APIs

### ISSUE THREAD

**Issue by buzentech** [airqo-platform/AirQo-frontend#17]
- What were you trying to achieve?
Point mobile app APIs to app engine database

- What are the expected results?
Similar nodes as those on the website should be able to display.
Sign up and sign in should work well.

- What are the received results?
![1](https://user-images.githubusercontent.com/55592057/72468764-f88dad00-37ee-11ea-911a-9581e1d1c6d3.jpg)

- What are the steps to reproduce the issue?
Download [apk](https://drive.google.com/open?id=1H6cmPs7ei2d6EALaSCHzrZSFPWGMwnY5)
Install apk
Run apk

- In what environment did you encounter the issue?
Android and iOS

- Which JIRA card relates to this issue?
[JIRA Link](https://airqoteam.atlassian.net/browse/DAT-106?atlOrigin=eyJpIjoiYTQxNDI4ZGI0NzFhNDA5YThmMDEyNWJlZmM1YWExMWUiLCJwIjoiaiJ9)

**Comment by buzentech** [comment]
Headers seem not to be working on the current App Engine environment. However, when similar source code is transferred and placed on a different App Engine environment, the headers work as expected.

**Comment by Baalmart** [comment]
How can I test out the IOS mobile app? Should I just update the mobile application?

**Comment by Baalmart** [comment]
Also, could you share the logs you are getting inside the App Engine log files? Command should be something like: _**gcloud app logs tail -s NAME_OF_APP**_

**Comment by Baalmart** [comment]
As requested yesterday, I also need clear steps of reproducing the issue on IOS so that I can observe the logs after running the command. At the moment, there are no logs I can see.

**Comment by buzentech** [comment]
An iOS version of the app for testing is being worked on.
