### ISSUE TITLE
[website] cannot upload image from WYSIWYG editor

### ISSUE THREAD

**Issue by danielogen** [airqo-platform/AirQo-frontend#174]
**What were you trying to achieve?**
Creating new blog post and upload images from within WYSIWYG editor

**What are the expected results?**
Upload images to a blog content 

**What are the received results?**
Error message: cannot upload an image
**What are the steps to reproduce the issue?**
Go to the website admin panel and create a new blog post. Try adding images in the blog post body. [screenshot attached] 
![Screenshot 2020-11-19 at 09 44 00](https://user-images.githubusercontent.com/15224992/99632074-af7d3980-2a4d-11eb-8ce4-ecd3752fbb72.png)

**In what environment did you encounter the issue?**
Chrome Version 86.0.4240.198 (Official Build) (x86_64)

Additional context
N/A

**Comment by adongot** [comment]
![image](https://user-images.githubusercontent.com/41906069/99638386-34b91c00-2a57-11eb-9dda-59de76721e41.png)
Use this to upload any image and the you can be able to use it.

**Comment by danielogen** [comment]
Hi @adongot, thanks for the clarification. Using the file/folder upload icon works well. Thanks!!
