### ISSUE TITLE
[website] cannot upload image to a draft blog post

### ISSUE THREAD

**Issue by danielogen** [airqo-platform/AirQo-frontend#179]
**What were you trying to achieve?**
Edit a draft blog post and upload images from within WYSIWYG editor

**What are the expected results?**
Upload images to a previously created draft blog post

**What are the received results?**
Nothing happens - No error message either 
What are the steps to reproduce the issue?
Go to the website admin panel and select a draft blog post. Try adding images in the blog post body. [screenshot attached]
![Screenshot 2020-12-02 at 12 05 47](https://user-images.githubusercontent.com/15224992/100851896-d6e4f500-3496-11eb-805e-6386c2098d99.png)

**Comment by danielogen** [comment]
Hi @buzentech , @adongot, 
I'm just following up on this task. Anything I can do to help??
cc: @Baalmart

**Comment by Baalmart** [comment]
No longer relevant. @danielogen
