### ISSUE TITLE
[netmanager] map page TypeError 

### ISSUE THREAD

**Issue by danielogen** [airqo-platform/AirQo-frontend#192]
- What were you trying to achieve?
Just clicking around the PM 2.5 AQI keys 
- What are the expected results?
No changes - just continue view map 
- What are the received results?
map filtered error as shown below
![Screenshot 2021-02-24 at 12 09 14](https://user-images.githubusercontent.com/15224992/108978045-40416200-769a-11eb-9972-ab0d3c7ca886.png)

- What are the steps to reproduce the issue?
```
cd AirQo-frontend/netmanager
npm install
```

> for MAC

`npm run stage-mac` OR `npm run prod-mac`

> for Windows

`npm run stage-pc` OR `npm run stage-pc`

- In what environment did you encounter the issue?
node 12.18.2

**Comment by ja-odur** [comment]
Resolved
