### ISSUE TITLE
Incorrect coordinates returned from backend APIs

### ISSUE THREAD

**Issue by buzentech** [airqo-platform/AirQo-frontend#20]
What were you trying to achieve?
Trying to zoom out of the map on the AirQo website homepage and see if any node falls outside Uganda.

What are the expected results?
No node should fall outside Uganda on the map.

What are the received results?
![Screenshot 2020-02-04 at 18 26 33](https://user-images.githubusercontent.com/55592057/73758801-26299e80-477c-11ea-9d2f-1f725fc7dd19.png)
![Screenshot 2020-01-31 at 19 54 19](https://user-images.githubusercontent.com/55592057/73758265-75230400-477b-11ea-8c41-90cfa83cc009.png)
![Screenshot 2020-01-31 at 19 55 24](https://user-images.githubusercontent.com/55592057/73758269-75230400-477b-11ea-8dfa-bad35a4741c3.png)

What are the steps to reproduce the issue?
Go the airqo.net homepage and zoom out of the map

In what environment did you encounter the issue?
The landing page of the main website - the map to be specific

Which JIRA card relates to this issue?
JIRA card is [here](https://airqoteam.atlassian.net/browse/DAT-122?atlOrigin=eyJpIjoiODM0MDhhYTE3NDZhNDFjY2E1ZDliMmMzNTU1MjE3NDEiLCJwIjoiaiJ9)

**Comment by Baalmart** [comment]
No longer an issue, with the implementation of sites.
