### ISSUE TITLE
Locations/Sites taking long to load in DATA EXPORT feature

### ISSUE THREAD

**Issue by Baalmart** [airqo-platform/AirQo-frontend#206]
**What were you trying to achieve?**
Trying to download a report for KCCA using the export feature of Netmanager within the KCCA account

**What are the expected results?**
Ability to select all filters comfortably and download a file accordingly.

**What are the received results?**
One of the filter options for Locations takes long to respond and on checking the browser console, the screenshot below indicates result.
![image](https://user-images.githubusercontent.com/1590213/113148722-e0128280-923a-11eb-9c5f-922c7ff532ba.png)

**What are the steps to reproduce the issue?**
Just visit the staging link of the platform and try to visit the **Export** side bar item, you will then try to filter the locations accordingly. You will notice that "no locations" will be generated. On checking the console, you will see the output indicated in the screenshot shared above.

**In what environment did you encounter the issue?**
 Google Chrome - Version 89.0.4389.90 (Official Build) (x86_64)

**Additional context**
N/A

**Comment by ja-odur** [comment]
I think there is a key conflict. The endpoint expects a key `pollutant` but we are supplying multiple pollutants.
![image](https://user-images.githubusercontent.com/39955305/113206807-95176000-9278-11eb-86a0-97d447dac374.png)

**Comment by danielogen** [comment]
> I think there is a key conflict. The endpoint expects a key `pollutant` but we are supplying multiple pollutants.
> ![image](https://user-images.githubusercontent.com/39955305/113206807-95176000-9278-11eb-86a0-97d447dac374.png)

Hi @ja-odur, thanks for pointing this out. However, the endpoint actually accepts multiple pollutants and location information (at least for the staging environment). I noticed you are testing the production URL. I will have to re-deploy `analytics` on production.
![Screenshot 2021-04-01 at 10 38 59](https://user-images.githubusercontent.com/15224992/113260068-8069b500-92d6-11eb-971b-a0f4f34de653.png)

**Comment by ja-odur** [comment]
Thanks. works well on staging.
