### ISSUE TITLE
[bug] disabling data export button active with some empty form fields

### ISSUE THREAD

**Issue by Baalmart** [airqo-platform/AirQo-frontend#211]
WHAT DO YOU EXPECT?
The download button should not be active in case any of the form fields are still empty

WHAT DO YOU GET?
The button is enabled when the two of the form fields (pollutants, location) are empty.

**Comment by ja-odur** [comment]
This is resolved by this [PR](https://github.com/airqo-platform/AirQo-frontend/pull/216)

**Comment by ja-odur** [comment]
This is resolved too
