### ISSUE TITLE
[bug] Overflow button missing on device management page

### ISSUE THREAD

**Issue by Baalmart** [airqo-platform/AirQo-frontend#212]
WHAT WERE YOU TRYING TO ACHIEVE?
Test out the responsiveness of Netmanager, see the overflow button on every page when in mobile view

WHAT ARE THE RESULTS YOU GET?
Overflow button disappears in mobile view when on the device management page

CONTEXT?
This closed PR: https://github.com/airqo-platform/AirQo-frontend/pull/209

**Comment by ja-odur** [comment]
This has been resolved
