### ISSUE TITLE
[Netmanager] Device Details Page not responsive

### ISSUE THREAD

**Issue by Baalmart** [airqo-platform/AirQo-frontend#222]
**What were you trying to achieve?**
View the details of the device in the device details page

**What are the expected results?**
Get a responsive view of the device details when on mobile.

**What are the received results?**
the view is not responsive in the mobile when you visit the device details page.

**What are the steps to reproduce the issue?**
Visit the _device details page_ and check out the responsiveness accordingly.

**In what environment did you encounter the issue?**
Google Chrome: Version 89.0.4389.114 (Official Build) (x86_64)

**Additional context**
None at the moment.

**Comment by ja-odur** [comment]
This is work still in progress

**Comment by ja-odur** [comment]
This has been resolved

**Comment by Baalmart** [comment]
This has been reopened after a recent concern by one of our stakeholders who originally raised the issue (`We urgently need a sort of mobile version for Netmanager`).
