### ISSUE TITLE
[Netmanager] Some Device Update Changes are not persisted

### ISSUE THREAD

**Issue by Baalmart** [airqo-platform/AirQo-frontend#224]
WHAT IS THE ISSUE?
Concerns about some device changes not being persisted to the DB accordingly, despite a success message showing.
On refresh, changes are still not visible.

CONTEXT?
This is in production environment. Chrome browser is the one used by the user.

**Comment by ja-odur** [comment]
@Baalmart could you share some examples in-order to replicate the issue.

**Comment by Baalmart** [comment]
> @Baalmart could you share some examples in-order to replicate the issue.
That is the same question I forwarded to the user, no response yet. Just left the issue here for future/easy reference/followup.

Quick assumption is around the integration of the platform and the website....they website implementers have (had) an additional database that they set up as a caching mechanism in case our system was down. Unfortunately, this database was not fully synchronised with the ones for Netmanager.

This needs more followup from my end....shall update us accordingly.....thanks!

**Comment by Baalmart** [comment]
> > @Baalmart could you share some examples in-order to replicate the issue.
> > That is the same question I forwarded to the user, no response yet. Just left the issue here for future/easy reference/followup.
> 
> Quick assumption is around the integration of the platform and the website....they website implementers have (had) an additional database that they set up as a caching mechanism in case our system was down. Unfortunately, this database was not fully synchronised with the ones for Netmanager.
> 
> This needs more followup from my end....shall update us accordingly.....thanks!

The issue is now clear, the issue is about the EDIT page of the Devices endpoint. After one "edits" the details of the page and navigates away to another TAB, the details are not persisted UNTIL they refresh the entire page. So for a user who does not know that they have to refresh, they might think that the data is not persisted. So the question now is: How to we maintain a good user experience while enabling the automatic refresh of the data in the local storage of the browser? @ja-odur

**Comment by Baalmart** [comment]
I gather that this was resolved, closing now. cc: @ja-odur
