### ISSUE TITLE
[Netmanager] Designing for dark mode in UI

### ISSUE THREAD

**Issue by Baalmart** [airqo-platform/AirQo-frontend#241]
**Is your feature request related to a problem? Please describe.**
This is a _low priority feature request._ There were some users who had dark mode enabled on their browsers so their experience when logging in was terrible since the text is not visible.

**Describe the solution you'd like**
In case one is in dark mode, the application should also be able to adjust accordingly and have text and other CSS aspects adjust accordingly instead of just having black screen.

**Describe alternatives you've considered**

- Either encourage the user to move away from dark mode or
- Make some system changes to support dark mode accordingly.

**Additional context**
There was feedback about poor user experience where one user was not able to see their password due to their enabled dark mode. At that time, the issue was that they were not able to login. Something that turned out to be a user browser preference/setting issue and not a system issue per se.

**Comment by divyanshiet** [comment]
Hey I think, I will be perfect for this issue, kindly assign it to me with hacktoberfest label
