### ISSUE TITLE
merge DEPLOY STATUS tab with EDIT tab

### ISSUE THREAD

**Issue by Baalmart** [airqo-platform/AirQo-frontend#247]
**Is your feature request related to a problem? Please describe.**
It is always frustrating when changes done during deployment do not reflect on the device details page. It also turns out that the EDIT tab of the device almost does the same tasks as the DEPLOY status tab of the device. 

**Describe the solution you'd like**
What if we merge EDIT and DEPLOY STATUS?

**Describe alternatives you've considered**
- Either have the two tabs much synchronised but remain separate.  
- Or have one tab which has all these fields that are present in the 2 separate tabs. As indicated in the screenshot below, the EDIT tab has a lot of misused space which can be put to good use accordingly if we bring over the device deployment and edit under one "roof".
![image](https://user-images.githubusercontent.com/1590213/116782838-1d656c80-aa94-11eb-90de-d356984a4fab.png)

**Additional context**
This issue closely relates with [issue-246](https://github.com/airqo-platform/AirQo-frontend/issues/246)
It was also highlighted that some of these tabs have fields that should not be taking a huge width on them.

**Comment by ja-odur** [comment]
This was resolved

**Comment by Baalmart** [comment]
This has been re-opened due to a recent similar issue (`Feature request: save option instead in addition to deploy`)
I guess we shall close these issues `only` after we get an approval from our stakeholders that originally brought the issue to light.
