### ISSUE TITLE
Automatically refresh content in cards

### ISSUE THREAD

**Issue by Baalmart** [airqo-platform/AirQo-frontend#248]
**Is your feature request related to a problem? Please describe.**
Always frustrating for the user whenever they have to refresh the entire web page in order to see their most recent changes in the EDIT tab.

**Describe the solution you'd like**
Immediately after a new edit has been made, the content of the web page must be refreshed with new content/edits.

**Describe alternatives you've considered**
No alternatives, just have the new edits./additions present after user action in any of the device details tabs. 

**Additional context**
None at the moment.....

**Comment by Baalmart** [comment]
This was resolved for the EDIT tab. We might also need to review the refresh for all pages starting with the table list view under device registry. Appears that the content for the device registry table list only change after a refresh of the entire page. How can we best handle the refresh of the devices list table without negatively affecting the user experience? cc: @ja-odur

**Comment by Baalmart** [comment]
I am not very sure/confident about the status of this issue, definitely needs more investigating. @ja-odur @NoahNsimbe

**Comment by Baalmart** [comment]
Thanks @ja-odur and @NoahNsimbe for any inout towards this.
I am unable to test out this feature since the device EDIT feature is misbehaving in the staging environment. I will go ahead and temporarily remove the resolved label.

**THE SCREENSHOT:**
<img width="1628" alt="Screenshot 2021-08-13 at 12 46 46" src="https://user-images.githubusercontent.com/1590213/129338762-d1d5179b-925c-4a43-a36f-82f8058b1c1b.png">

**Comment by ja-odur** [comment]
@Baalmart I am closing this. it seems outdated
