### ISSUE TITLE
improve the user experience of the Device component graphs

### ISSUE THREAD

**Issue by Baalmart** [airqo-platform/AirQo-frontend#249]
**Is your feature request related to a problem? Please describe.**
The current component graphs are not very user friendly since it kinda frustrating for the user to align a date/time to particular spot on the line graphs

**Describe the solution you'd like**
The x axis of these component graphs should have few details to avoid congestion and the line graphs should also indicate the time when one hovers over a field.

**Describe alternatives you've considered**

- A user should be able to zoom into a graph to see more details.
- The height scale of each component graph could be smart and adjust according to the maximum and minimum for any component's values.
- The values of the x axis can also just show the first, middle and last values. Since no user might have the time/energy to align the axis readings with the spot in the line graph
- Add grid lines?

**Additional context**
As seen in the attached screenshot it is hard to map an x axis reading to a line graph point.
![image](https://user-images.githubusercontent.com/1590213/116783320-c90fbc00-aa96-11eb-9475-f1a073369167.png)

**Comment by ja-odur** [comment]
@Baalmart  If you hover on the map, a poppup showing a details of the point closes ( or vertically aligned with the point) appears. It's how the chart library works. Not need of a vertical line. The details shown include the date and value corresponding to the point. Please verify, otherwise I think this issue can be closed.

**Comment by Baalmart** [comment]
Outdated issues. Thanks @ja-odur for the clarification.
