### ISSUE TITLE
Log in on netmanager produces errors

### ISSUE THREAD

**Issue by sserurich** [airqo-platform/AirQo-frontend#255]
**What were you trying to achieve?**
 Testing out that the[ issue ](https://github.com/airqo-platform/AirQo-frontend/issues/84) is resolved
  To ensure the issue is reproduced, ran the netmanager locally (dev environment) and tried to login (when Auth Service wasn't running" 
**What are the expected results?**
   A clearer succinct message  instead of system crushing with these error

**What are the received results?**
Type errors with a yellow screen as shown in screenshot below
![image](https://user-images.githubusercontent.com/8258229/117124300-d4b5f800-ada0-11eb-8120-6a1ed48ddabc.png)

**What are the steps to reproduce the issue?**
follow steps in this [PR](https://github.com/airqo-platform/AirQo-frontend/pull/254) but start the application in development environment.
  ensure auth service isn't running and login 
**In what environment did you encounter the issue?**
 - OS: windows 10
 - Version 10

**Additional context**
Any other information you would like to share?

**Comment by Baalmart** [comment]
I guess this is no longer existent. @ja-odur @sserurich
