### ISSUE TITLE
Presistent Error Notification

### ISSUE THREAD

**Issue by danielogen** [airqo-platform/AirQo-frontend#265]
**What were you trying to achieve?**
Checking offline errors [PR-259](https://github.com/airqo-platform/AirQo-frontend/pull/259)
**What are the expected results?**
View offline errors on login, forgot password and request access

**What are the received results?**
The offline error notification is persistent across forgot password and request access. Some sort of state variable NOT changed
**What are the steps to reproduce the issue?**
Run this PR https://github.com/airqo-platform/AirQo-frontend/pull/259. Test offline error on forgot password screen and move to request access screenshot. You will see the offline notification even before trying to request access.
**In what environment did you encounter the issue?**
 - OS:  iOS
 - Version: 10.14.6

**Additional context**
Any other information you would like to share?
![Screenshot 2021-05-25 at 09 25 27](https://user-images.githubusercontent.com/15224992/119450170-359b7500-bd3c-11eb-9543-c22f25fcdb1d.png)

**Comment by Baalmart** [comment]
We need to review the status of this, I guess it was fixed? @danielogen

**Comment by Baalmart** [comment]
I am not very sure about the status of this one. But appears to be a good first issue just in case it has not yet been resolved. @ja-odur
