### ISSUE TITLE
Mobile app docs

### ISSUE THREAD

**Issue by NoahNsimbe** [airqo-platform/AirQo-frontend#296]
**Is your feature request related to a problem? Please describe.**
User needs to access docs for the app

**Describe the solution you'd like**
To be discussed...🙏

**Describe alternatives you've considered**
None

**Additional context**
[PLAT-246](https://airqoteam.atlassian.net/browse/PLAT-246)

**Comment by PaulZana** [comment]
Will have to share my thoughts around the corner(trying to get hold of the ux)
