### ISSUE TITLE
categories and map are blank on device management page (staging)

### ISSUE THREAD

**Issue by Baalmart** [airqo-platform/AirQo-frontend#298]
**What were you trying to achieve?**
Within the staging environment, check out the device management page to analyse network performance

**What are the expected results?**
The map and the cards should return the information needed

**What are the received results?**
All cards and map are blank
<img width="899" alt="Screenshot 2021-07-08 at 19 58 20" src="https://user-images.githubusercontent.com/1590213/124962758-ae723a00-e027-11eb-926a-2b5e7736dbe2.png">
<img width="1445" alt="Screenshot 2021-07-08 at 19 57 53" src="https://user-images.githubusercontent.com/1590213/124962764-b0d49400-e027-11eb-903c-b4028f4093d6.png">

**What are the steps to reproduce the issue?**
Just visit the device management page ----in the STAGING environment.

**In what environment did you encounter the issue?**
Google Chrome

**Additional context**
N/A

**Comment by ja-odur** [comment]
Resolved
