### ISSUE TITLE
From frontend, Site Registry data is the same for both organisaitons

### ISSUE THREAD

**Issue by Baalmart** [airqo-platform/AirQo-frontend#304]
**What were you trying to achieve?**
Explore the site data for the two organisations in Netmanager

**What are the expected results?**
The site data for the 2 organisations should be different.....

**What are the received results?**
The site data for KCCA is the same as that one for AirQo.......
<img width="483" alt="Screenshot 2021-07-15 at 23 36 08" src="https://user-images.githubusercontent.com/1590213/125854114-111095de-ece5-4e09-b74e-d4d7b7faeb1d.png">
<img width="491" alt="Screenshot 2021-07-15 at 23 35 30" src="https://user-images.githubusercontent.com/1590213/125854119-8ee13c4c-6b94-4d1a-9e43-3e55de6f8d34.png">

**What are the steps to reproduce the issue?**
Just login into the platform on both the organisations and navigate towards the Site Registry section

**In what environment did you encounter the issue?**
Google chrome....

**Additional context**
N/A

**Comment by ja-odur** [comment]
This has been resolved
