### ISSUE TITLE
Bad data shown in the dashboard graphs

### ISSUE THREAD

**Issue by Baalmart** [airqo-platform/AirQo-frontend#308]
**What were you trying to achieve?**
View the analytics graphs in the dashboard.
There’s an old principle in computer science: “Garbage In, Garbage Out”. In the context of data visualization, this means that some bad data is leading to bad visualizations as shown in the spikes of the attached screenshot. 

**What are the expected results?**
View all the graph details without any data gaps/issues detected in the visuals.
Starting with the basics: is our data clean? Do we use checks at every stage the data goes through — collection, sourcing, cleaning, and compiling — before it is visualized. Common errors include data duplication, missed data, NA values not marked, and so on.

**What are the received results?**
Some of the graphs showcase some inconsistent visualisations as shown in the graphs below:
<img width="675" alt="Screenshot 2021-07-22 at 04 37 58" src="https://user-images.githubusercontent.com/1590213/126579532-d5245ace-4233-40f0-acdc-ab13c85d2fb7.png">

**What are the steps to reproduce the issue?**
Just visit the staging link accordingly

**In what environment did you encounter the issue?**
Google Chrome Version 91.0.4472.114 (Official Build) (x86_64)

**Additional context**

- This was brought about during the demo.
- Also, this comes from the background that since the dashboard is going to be for public consumption, it should not indicate any unreliability in the network.
- [Common Mistakes That Lead to Bad Data Visualization](https://humansofdata.atlan.com/2016/09/common-mistakes-bad-data-visualization/)
- [How to deal with outliers](https://cxl.com/blog/outliers/)
- A thought from one team member was:

>  I had a look at this and the very high values are the problem. One solution is to set limits such that if a pm value is outside those limits, it's replaced by say the average or something. But then what happens when it is not a one off but a device is consistently streaming bad data

**Comment by Baalmart** [comment]
cc: @lilly-muyama , we shall need your input about how to handle outliers

**Comment by ja-odur** [comment]
resolved
