### ISSUE TITLE
Redirect all AirQo domains point to the default one (.net)

### ISSUE THREAD

**Issue by Baalmart** [airqo-platform/AirQo-frontend#310]
**Is your feature request related to a problem? Please describe.**
AirQo has many domain names, tracking the analytics for all these could be hard to manage.

**Describe the solution you'd like**
Redirect all of them to the default domain name which is tracked. This will make it easy to get analytics of all our visitors all in one place.

**Describe alternatives you've considered**
N/A

**Additional context**
This was suggested by Paul Z in one of the demo meetings....

**Comment by Baalmart** [comment]
all are pointing to the same URL, so we can still track the analytics even with different domain names.

**Comment by 123MwanjeMike** [comment]
This was addressed by @123MwanjeMike
