### ISSUE TITLE
view deployment details of a device

### ISSUE THREAD

**Issue by Baalmart** [airqo-platform/AirQo-frontend#333]
**Is your feature request related to a problem? Please describe.**
A user would like to view the deployment date and time on the platform.
Related to #354

**Describe the solution you'd like**
Being able to easily locate any device's deployment date and time....

**Describe alternatives you've considered**
- just some additional details in the device overview section to allow user view deployment details of the device
- Have one generic page/tab for Site Activities where the user can be able to select type of activity (Deployment/Recallment/Maintenance) and then view the respective details as required.

**Additional context**
Pulled from a service desk ticket.

**Comment by NoahNsimbe** [comment]
Related to #354

**Comment by Baalmart** [comment]
I think this was addressed.
