### ISSUE TITLE
Locate feature's map overlay options not showing

### ISSUE THREAD

**Issue by Baalmart** [airqo-platform/AirQo-frontend#334]
**What were you trying to achieve?**
Struggling with the locate feature on nonmanager. Looks like it isn't actually working. I can draw a polygon and all but it can't let me drop the 'pins' for probable locations.

**What are the expected results?**
Ability to user the feature as expected.
The map overlay options should show up, the ones which enable one to draw a polygon.

**What are the received results?**
 I can draw a polygon and all but it can't let me drop the 'pins' for probable locations.
The map overlay options are not showing

**What are the steps to reproduce the issue?**
Head over to the platform and navigate towards the LOCATE feature (sidebar option) accordingly.
Attempt to draw a polygon using the map overlay options in the top right corner.

**In what environment did you encounter the issue?**
Google chrome Version 92.0.4515.107 (Official Build) (x86_64)

**Additional context**
It appears that these map options appear in some browsers as we have been made aware. So this is more of a browser compatibility issue or something along those lines.
A screenshot to show the missing map manipulation options
<img width="1635" alt="Screenshot 2021-07-26 at 12 39 30" src="https://user-images.githubusercontent.com/1590213/126969328-8e6587cc-dcf5-4795-8304-6f8628a9404d.png">

**Comment by Baalmart** [comment]
So the issue description has been updated accordingly to reflect the actual feedback from the user. @lilly-muyama @ja-odur

**Comment by ja-odur** [comment]
Duplicate issue
