### ISSUE TITLE
Add Input validation when deploying devices

### ISSUE THREAD

**Issue by Baalmart** [airqo-platform/AirQo-frontend#336]
**Is your feature request related to a problem? Please describe.**
We keep getting the 'some fields missing' error while we try to deploy devices. 

**Describe the solution you'd like**
Might help if it could flag for the user

**Describe alternatives you've considered**
N/A

**Additional context**
This was raised by one of the active netmanager users

**Comment by ja-odur** [comment]
This has been resolved
