### ISSUE TITLE
 issue with profile picture upload

### ISSUE THREAD

**Issue by Baalmart** [airqo-platform/AirQo-frontend#341]
**What were you trying to achieve?**
Upload profile picture 

**What are the expected results?**
A user should be able to easily upload pictures.

**What are the received results?**
Upload profile picture seems not work as expected. An attempt to upload but nothing changes

**What are the steps to reproduce the issue?**
In the system's frontend

**In what environment did you encounter the issue?**
N/A

**Additional context**
Shared by active user.
This issue could also be linked to the re-implementation of the entire picture upload user case where most of the work will be moved to the backend accordingly. And in the process, treat a photo as an entity.

**Comment by Baalmart** [comment]
PR is still open, pending some few more requested hotfixes. @ja-odur @NoahNsimbe

**Comment by Baalmart** [comment]
Hi @NoahNsimbe  and @ja-odur 
It appears that the **photo upload issue** is still present in both the recently deployed staging and production.
Please see attached screenshots shared below.

**SUGGESTION:**
I suggest that we wait for a corresponding feature request ([frontend-issue-276](https://github.com/airqo-platform/AirQo-frontend/issues/276)) of photo registry to properly support any features related to photos.

**THE SCREENSHOTS:**
<img width="960" alt="Screenshot 2021-08-13 at 12 20 04" src="https://user-images.githubusercontent.com/1590213/129336576-0b7c92b4-d22f-4a69-b00f-c9faa80e5e79.png">

<img width="977" alt="Screenshot 2021-08-13 at 12 21 45" src="https://user-images.githubusercontent.com/1590213/129336655-d50c01ad-5188-4380-a353-836b17a0a0ac.png">

**Comment by Baalmart** [comment]
I am going ahead to remove the resolved label from this....in the time being.... @ja-odur

**Comment by ja-odur** [comment]
@Baalmart I have just been able to upload profile pic on staging.  Not sure if the changes have been migrated to staging.
The staging screenshot does not show the cors error. Please re-test and confirm on staging.

**Comment by Baalmart** [comment]
Yeah, it has worked on the second attempt. It failed on the first attempt.
I am still curious why it refused to reflect the changes on my first attempt.
Let me close issue for now but we need to closely monitor to avoid: "it works sometimes"
Perhaps further investigations and monitoring? @ja-odur
