### ISSUE TITLE
remove GPS coordinate inputs during device deployment

### ISSUE THREAD

**Issue by Baalmart** [airqo-platform/AirQo-frontend#352]
**Is your feature request related to a problem? Please describe.**
It is a bit redundant to have both the input forms for GPS coordinates and also request for a site which has the GPS coordinate

**Describe the solution you'd like**
remove GPS coordinate inputs during device deployment

**Describe alternatives you've considered**
Just request for a site

**Additional context**
None, in line with recent updates about Sites...

**Comment by ja-odur** [comment]
The sole reason we need devices to have their own coordinates if for representation on the map, otherwise, multiple devices on the map will be superimposed. This was discussed a while back. All maps (netmanager/website/possibly mobile) use this info because of this particular reason @Baalmart

**Comment by Baalmart** [comment]
> The sole reason we need devices to have their own coordinates if for representation on the map, otherwise, multiple devices on the map will be superimposed. This was discussed a while back. All maps (netmanager/website/possibly mobile) use this info because of this particular reason @Baalmart

Thanks, this makes a lot of sense. @ja-odur
