### ISSUE TITLE
Date of Deployment is confusing

### ISSUE THREAD

**Issue by Baalmart** [airqo-platform/AirQo-frontend#354]
**Is your feature request related to a problem? Please describe.**
At the time of `device deployment`, the user is confused by that date of deployment which always shows the current date of operation

Related to  #333

<img width="884" alt="Screenshot 2021-08-06 at 08 51 33" src="https://user-images.githubusercontent.com/1590213/128462671-6bf9202d-f510-4b83-8d4d-5f3f0083e1fb.png">

**Describe the solution you'd like**
That date should also indicate the date at which the device was deployed---especially for deployed devices.

**Describe alternatives you've considered**

- That date should also indicate the date at which the device was deployed---especially for deployed devices.
- Or just remove it and only leave a blank date field for the use

**Additional context**
This was picked from a member of the HW team

**Comment by ja-odur** [comment]
@Baalmart It seems the deployment date is not captured anywhere within the device details. Unless I am missing something. Hence this field will not be shown anywhere (edit and deploy sections of a device)

**Comment by Baalmart** [comment]
PR is still open, pending some few more requested hotfixes. @ja-odur @NoahNsimbe

**Comment by Baalmart** [comment]
There are still some pending issues regarding this **issue of deployment date**, despite the most enhancements. So I will go ahead and remove the `resolved` label from this. @ja-odur

**Comment by Baalmart** [comment]
This was resolved, we just need to do some data updates for all devices accordingly. Thanks @ja-odur
