### ISSUE TITLE
Customise dashboard charts using a custom time range

### ISSUE THREAD

**Issue by NoahNsimbe** [airqo-platform/AirQo-frontend#368]
**What were you trying to achieve?**
Customise any dashboard chart by specifying a time range

**What are the expected results?**
Expected the chart title and axes to reflect the selected time ranges

**What are the received results?**
The chart title and axes didn't change 

**What are the steps to reproduce the issue?**
Customise any dashboard chart by specifying a custom time range then review the chart axes and title after it has loaded

**In what environment did you encounter the issue?**
 - OS: Ubuntu
 - Version 21.04

**Additional context**
None

**Comment by NoahNsimbe** [comment]
This seems to have been resolved cc @ja-odur @Baalmart. Shall close this issue if no reservations.

**Comment by Baalmart** [comment]
Thanks @NoahNsimbe
