### ISSUE TITLE
Maintenance log persists on table after deletion

### ISSUE THREAD

**Issue by NoahNsimbe** [airqo-platform/AirQo-frontend#369]
**What were you trying to achieve?**
Delete a maintenance log

**What are the expected results?**
Expected the maintenance log to disappear from the maintenance log table after cliking the delete icon

**What are the received results?**
The log remained in the table until I had to refresh the browser tab

**What are the steps to reproduce the issue?**
Create a maintenence log then delete it from the table using the delete icon

**In what environment did you encounter the issue?**
 - OS: Ubuntu
 - Version 21.04

**Additional context**
None

**Comment by Baalmart** [comment]
PR is still open, pending some few more requested hotfixes. @ja-odur @NoahNsimbe

**Comment by Baalmart** [comment]
This was resolved and functions as expected. Thanks @ja-odur
