### ISSUE TITLE
Enable auto resize for the locate map to fit into the available space

### ISSUE THREAD

**Issue by NoahNsimbe** [airqo-platform/AirQo-frontend#370]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to scroll or resize my browser window inorder to see controls of the map on the locate page

**Describe the solution you'd like**
Auto scale the map to fit in the available space without having a user to scroll to the far right or resize their browser window inoder to see the map controls

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by Baalmart** [comment]
Awesomely executed! Thanks @ja-odur
