### ISSUE TITLE
"Expand" the deploy/Not Deployed State with more options

### ISSUE THREAD

**Issue by Baalmart** [airqo-platform/AirQo-frontend#380]
**Is your feature request related to a problem? Please describe.**
At the moment, the user managing the network is not able able to easily track the status of a newly created device in the production assembly line accordingly. The current implementation of netmanager does not offer options to monitor the hardware production process.

**Describe the solution you'd like**
Expanding the deploy/not deployed state with more options.
In assembly line =>  In-stock and ready  => Deployed => Un deployed -> Recalled for maintenance -> Decommissioned. 

**Describe alternatives you've considered**
- Utlliization of the "new" `status` field for the deployment status of the device instead of using the `isActive` field
- We need to review the UI colors we shall use for the different statuses. Currently we are use green for` deployed` and red for `undeployed`.

**Additional context**
This was picked up as a feature request from the recently concluded hardware demo.
API details:
We are using the update endpoint for devices where the updated field is `status`
There is already a device status field on the platform which we can take advantage of for this. Screenshot follows shortly:
<img width="1241" alt="Screenshot 2021-08-30 at 12 47 37" src="https://user-images.githubusercontent.com/1590213/131321134-60be582a-741a-42ec-a458-b241706a8072.png">

**Comment by Baalmart** [comment]
1. Also, just been in discussions about the collocation feature whose requirements are being generated, there is a need to  have **deployable** status among the valid reasons.
2.  Also, what happened to those changes about this issue that were demoed sometime back. @123MwanjeMike @NoahNsimbe @ja-odur 


let me reopen this issue....

**Comment by 123MwanjeMike** [comment]
> 1. Also, just been in discussions about the collocation feature whose requirements are being generated, there is a need to  have **deployable** status among the valid reasons.
> 
>     2. Also, what happened to those changes about this issue that were demoed sometime back. @123MwanjeMike @NoahNsimbe @ja-odur
> 
> 
> let me reopen this issue....

I think the issue was re assigned to @Codebmk

**Comment by 123MwanjeMike** [comment]
This was addressed by #521
