### ISSUE TITLE
Rename generated names

### ISSUE THREAD

**Issue by ja-odur** [airqo-platform/AirQo-frontend#381]
**What were you trying to achieve?**
Rename generated name columns on site and device registry tables to site_id (site_code) and device_id respectively

**What are the expected results?**

**What are the received results?**

**What are the steps to reproduce the issue?**

**In what environment did you encounter the issue?**

**Additional context**
Any other information you would like to share?

**Comment by Baalmart** [comment]
This was addressed. Thanks @ja-odur
