### ISSUE TITLE
Resolve the “last refreshed 2 hours” from the Map of Staging.

### ISSUE THREAD

**Issue by ja-odur** [airqo-platform/AirQo-frontend#385]
**What were you trying to achieve?**
Last refreshed on the map nodes (netmanager) shows 2 hours but running the device tests, indicates the device last pushed  2 minutes ago. Test device used `aq_67`

**What are the expected results?**

**What are the received results?**

**What are the steps to reproduce the issue?**

**In what environment did you encounter the issue?**

**Additional context**
Any other information you would like to share?

**Comment by ja-odur** [comment]
Tested this out. Seems the time field on each events record is about 5 hours behind. This is the endpoint used to get recent events (https://staging-platform.airqo.net/api/v1/devices/events?tenant=airqo&recent=yes)

I fast tracked using on device aq_67, the time field at the time writing this comment was 2021-08-17T12:56:10.000Z` but running device tests, it says the device last pushed 2 minutes ago. Either we are not getting the most recent records or the pipeline is changing the time field. @Baalmart

**Comment by Baalmart** [comment]
> Tested this out. Seems the time field on each events record is about 5 hours behind. This is the endpoint used to get recent events (https://staging-platform.airqo.net/api/v1/devices/events?tenant=airqo&recent=yes)
> 
> I fast tracked using on device aq_67, the time field at the time writing this comment was 2021-08-17T12:56:10.000Z` but running device tests, it says the device last pushed 2 minutes ago. Either we are not getting the most recent records or the pipeline is changing the time field. @Baalmart

Thanks for these notes @ja-odur , we might need a working meeting on all pipeline related issues.

**Comment by Baalmart** [comment]
Just checked this out recently and it seems like there is some bit of more quality checks to make before we consider this as done. The issues seems to still be present, as seen in the attached screenshot. @ja-odur 
<img width="928" alt="Screenshot 2021-08-30 at 12 27 17" src="https://user-images.githubusercontent.com/1590213/131318193-06168a84-c9c5-405f-823a-199102e3ca01.png">

**Comment by Baalmart** [comment]
This was resolved. Thanks.
