### ISSUE TITLE
Issues with the data export feature.

### ISSUE THREAD

**Issue by Baalmart** [airqo-platform/AirQo-frontend#393]
**What were you trying to achieve?**
The download (data export) should handle data download for long period of times. More details of the issue are provided below.

**What are the expected results?**
Ability to easily download data conveniently.

**What are the received results?**

- Couldn't download data for a longer period of time.. this is still present. nothing happens and we had talked about it earlier and we said for now maybe the team can explicitly inform users what can be downloaded
- For data covering small periods like the one requested i.e. from 10th to 19th september 2020, below are the points that might be improved. 
- data incompleteness for the period (I have attached the results downloaded from the platform and the one processed & generated from BigQuery, for further review by the team.
- Need to arrange/sort the data in particular order..(either descending or ascending based on time, ascending might be the best option, it's kinder random right now.

**What are the steps to reproduce the issue?**
Just check out the platform feature for data export, available for all user types.

**In what environment did you encounter the issue?**
N/A

**Additional context**
Shared by Richard via service desk

**Comment by NoahNsimbe** [comment]
This looks related #206

**Comment by Baalmart** [comment]
Works fine now. Just realised that data ---nothing happens, not notifications sent to the user and no download happens. An example of this is shown the attached screenshot. But all the rest of the issues are properly addressed.  @ja-odur @NoahNsimbe 
<img width="1330" alt="Screenshot 2021-09-27 at 22 58 31" src="https://user-images.githubusercontent.com/1590213/134976567-3309ba5f-b9d9-45d4-a743-2d76cc422673.png">
