### ISSUE TITLE
Share contextual data within the mobile application

### ISSUE THREAD

**Issue by Baalmart** [airqo-platform/AirQo-frontend#394]
**Is your feature request related to a problem? Please describe.**
This is in relation to the `mobile application` where a user would like to share metadata about observations within their neighbourhood. This is different from the usual feedback or AQI camera feature since the data the user share is more detailed.

**Describe the solution you'd like**
Something custom for contextual data  where a user can get to share observations linked to air quality measurements

**Describe alternatives you've considered**

- A feature that gathers logs just like how you would have it in a spreadsheet document.
- Perhaps add some pictures to the logs being shared.
- Generally, the ability to share detailed notes with timestamp, site name/ID, tags and a description of the observations. 

**Additional context**
This feature request has been picked up from one of the AirQo team internal users.
![feature-request](https://user-images.githubusercontent.com/1590213/130979384-f35e4935-de19-4204-9166-fe4350ce99e5.jpeg)

**Comment by NoahNsimbe** [comment]
@Baalmart is this still needed??

**Comment by Baalmart** [comment]
Yes @NoahNsimbe it is still relevant!

All part of participatory air quality monitoring.
