### ISSUE TITLE
Review the details we show in the maintenance logs

### ISSUE THREAD

**Issue by Baalmart** [airqo-platform/AirQo-frontend#398]
**Is your feature request related to a problem? Please describe.**
Kind of frustrating for the user that they cannot be able to tell when they actually maintained the device

**Describe the solution you'd like**

- Show maintenance details of the device. 

**Describe alternatives you've considered**

- Remove fields like next maintenance date to create space for the actual maintenance date.
- Harmonise the definition of some fields like maintenance type and definition. Appears some fields take in the same type of data. Could we just stay with one of the fields instead of both?
<img width="1418" alt="Screenshot 2021-08-27 at 10 51 19" src="https://user-images.githubusercontent.com/1590213/131093386-734f1ea3-f165-4ec6-8452-0a62e0ab7a65.png">

**Additional context**
Picked from the hardware demo.

**Comment by ja-odur** [comment]
This has been fixed
