### ISSUE TITLE
review the device registry table's search functionality

### ISSUE THREAD

**Issue by Baalmart** [airqo-platform/AirQo-frontend#408]
**What were you trying to achieve?**
search device by ID

**What are the expected results?**
filtered and correct results of the search

**What are the received results?**
review the device search functionality, sometimes just putting the number like 19 just returns many details.

**What are the steps to reproduce the issue?**
Just head over to Netmanager and search for devices 19, 20

**In what environment did you encounter the issue?**
Google chrome

**Additional context**
None

**Comment by ja-odur** [comment]
Closed
