### ISSUE TITLE
Automatically refresh all platform (device details) content after device deployment

### ISSUE THREAD

**Issue by Baalmart** [airqo-platform/AirQo-frontend#411]
**Is your feature request related to a problem? Please describe.**
It is kinda confusing for the user whenever they finish deployment, go to check the site for site details and do not find the respective device recently added. They have to first refresh to see it.

**Describe the solution you'd like**
Handle the automatic refreshes whenever one visits the different tables like site registry and device registry.  

**Describe alternatives you've considered**
Can we perhaps inform the user that they have to refresh just like how it is done in Github when a PR has received some new commits?.

**Additional context**
Feedback gotten from a HW unit user recently. Informed me that some members who are not very aware might think that things are not working.

**Comment by ja-odur** [comment]
This can not be replicated, marking it as resolved

**Comment by Baalmart** [comment]
> This can not be replicated, marking it as resolved
Okay, let me share more clarifying notes @ja-odur 
On using staging environment to test out....
After a device `aq_52` was recalled, I went over to check the site details and still found the device attached to the Site (`Busabala, Wakiso`). The details only disappeared after refreshing the Site details page.
Please see screenshots for more details, they are all numbered (in red ink: 1,2,3,4) in their order of task operation.
<img width="1453" alt="Screenshot 2021-09-02 at 14 03 55" src="https://user-images.githubusercontent.com/1590213/131833539-759fe107-02b0-4796-9830-fe90455375d9.png">
<img width="1411" alt="Screenshot 2021-09-02 at 14 04 29" src="https://user-images.githubusercontent.com/1590213/131833547-7977905f-4c0f-478f-98a5-c7566a3d0d54.png">
<img width="1437" alt="Screenshot 2021-09-02 at 14 05 51" src="https://user-images.githubusercontent.com/1590213/131833560-d7f89a0d-f9ec-48f2-85be-7adb9168670a.png">
<img width="1394" alt="Screenshot 2021-09-02 at 14 10 47" src="https://user-images.githubusercontent.com/1590213/131833880-3b5b0c87-c340-4035-bf2b-ffcdabdf1aa7.png">

**Comment by Baalmart** [comment]
I am unable to properly test this out in staging. Somehow system hangs when I try to load site registry after a recall activity. Shall continue investigating collaboratively.
<img width="1651" alt="Screenshot 2021-09-13 at 19 42 59" src="https://user-images.githubusercontent.com/1590213/133124404-4b0717c1-0c2d-4587-9782-863e9169e079.png">

**Comment by Baalmart** [comment]
Not yet sure about the state of this. Tests in staging not yet very satisfactory. @NoahNsimbe @ja-odur

**Comment by NoahNsimbe** [comment]
This was resolved
