### ISSUE TITLE
View user/candidates details after creation/confirmation

### ISSUE THREAD

**Issue by Baalmart** [airqo-platform/AirQo-frontend#419]
**Is your feature request related to a problem? Please describe.**
Incase I need to review the candidate after approval, like looking at his/her details (reason why he requested data, organisation attached i.e. details that they submit on for request).. seems I can't access that.. I can only now view them as users (and that section misses that info). can advise accordingly.

**Describe the solution you'd like**
Enable the admin user to view the details of the user under the users section

**Describe alternatives you've considered**
Just have a clickable list of users
Just have a collapsible navigation where one can view more details of the user accordingly.

**Additional context**
Picked from a service desk issue.

**Comment by 123MwanjeMike** [comment]
For this, I am going to add a button under actions for "_details_"(just before update) that will avail the admin with the application info as required. cc @Baalmart @ja-odur 
![image](https://user-images.githubusercontent.com/41787587/156775970-498ab1f4-65c1-428d-a044-dc96ae297dd2.png)

**Comment by Baalmart** [comment]
Thanks @123MwanjeMike , sounds like a great idea. Additionally:

1. The admin wants to see the timestamp when that request came through.
2. Also, they want to be able to retrieve that data after the user has been confirmed. In other-words, in the Users table, the admin would like to also be able to view `more details` for a confirmed user.

> For this, I am going to add a button under actions for "_details_"(just before update) that will avail the admin with the application info as required. cc @Baalmart @ja-odur ![image](https://user-images.githubusercontent.com/41787587/156775970-498ab1f4-65c1-428d-a044-dc96ae297dd2.png)

Thanks

**Comment by Baalmart** [comment]
> Thanks @Baalmart We may also need to update the api to:
> 
> 1. capture the timestamps for when request was submitted and when it was confirmed/rejected.
> 2. retain the records of candidates after request confirmation

True, all sounds good. Great suggestions!
