### ISSUE TITLE
Rename deployment checkbox

### ISSUE THREAD

**Issue by ja-odur** [airqo-platform/AirQo-frontend#431]
**What were you trying to achieve?**
 rename `Primary for this location` deployment checkbox to `primary for this site`

**What are the expected results?**

**What are the received results?**

**What are the steps to reproduce the issue?**

**In what environment did you encounter the issue?**

**Additional context**
Any other information you would like to share?

**Comment by Baalmart** [comment]
All works as expected, thanks @ja-odur
