### ISSUE TITLE
Add a loading progress bar for the device list table. 

### ISSUE THREAD

**Issue by Baalmart** [airqo-platform/AirQo-frontend#440]
**Is your feature request related to a problem? Please describe.**
When the devices list is not yet present, there is not loading sign so it confuses the user when they see: "no devices found". And then after like a minute, they appear.

**Describe the solution you'd like**
Just to improve the UX for the user, add a loading progress bar for the device list table. 

**Describe alternatives you've considered**
We can grey out the content, as a form of "loader"

**Additional context**
See attached screenshot. 
<img width="1377" alt="Screenshot 2021-09-13 at 19 33 38" src="https://user-images.githubusercontent.com/1590213/133122658-62beb088-4163-418a-af0e-c16a1926fab0.png">

**Comment by 123MwanjeMike** [comment]
Was addressed by @Codebmk
