### ISSUE TITLE
refactor/review multitenancy system implementation from the frontend perspective

### ISSUE THREAD

**Issue by Baalmart** [airqo-platform/AirQo-frontend#502]
**Is your feature request related to a problem? Please describe.**
First time users were not able to easily access the system. As described in the attached screenshot. For first time users, that organization is very confusing.
![Access](https://user-images.githubusercontent.com/1590213/132665204-cbb6750b-eb35-4fe1-89cf-269d4cc475d7.JPG)

Afterwards, this was addressed by removing the org field and handling it from the backend. Default cases are airqo and other orgs require one to add a path in the url, example: /kcca as shown below
<img width="1336" alt="Screenshot 2022-02-18 at 17 56 52" src="https://user-images.githubusercontent.com/1590213/154706775-d4de62c9-b5da-4d4f-bfa2-28928986e790.png">

**Describe the solution you'd like**
Still handling the tenancy without requiring additional user actions when visiting pages.

**Describe alternatives you've considered**
- Add airqo as the first path before other the urls, example: https://platform.airqo.net/airqo/login instead of current one which is: https://platform.airqo.net/login/kcca so that is visible.
- Using subdomains.
- 

**Additional context**
Picked from a service desk issue. The proposed solutions could also be related to this[ open API-PR-575](https://github.com/airqo-platform/AirQo-api/pull/575)

**Comment by 123MwanjeMike** [comment]
**More alternatives to consider**
1. User selecting organisation from list of curated organisations on sign-in form.
2. Deriving user's organisation from login email domain.
3. Using shared database for login, backend then determines which organisation user belongs to.
5. Using a shared database for all tenant data
4.

**Comment by 123MwanjeMike** [comment]
Intresting insights to pick from [this article](https://medium.com/@larbisahli/multi-tenant-application-architecture-with-node-js-express-and-postgresql-3b94ea270a72) in relation to this issue
