### ISSUE TITLE
Enhance the view of the Description column in the Candidates list

### ISSUE THREAD

**Issue by Baalmart** [airqo-platform/AirQo-frontend#509]
**Is your enhancement request related to a problem? Please describe.**
The current list views under `Candidates` needs some review, especially the row for Description. When the content of that column is a lot, it requires one to first scroll and read from a narrow column of that content. Please see screenshot below:
<img width="1358" alt="Screenshot 2022-02-21 at 17 18 51" src="https://user-images.githubusercontent.com/1590213/154973526-26b4e65b-effd-46a8-ab39-8d51dfa86800.png">

**Describe the solution you'd like**
Present the content in a more readable view, especially for cases where the Description has a lot of information?

**Describe alternatives you've considered**
- implement a pop up window and present a screenwide view of the Description column content.
- Just have a way in which this content is spread "collapsed" when clicked but remains hidden in default mode
- Any other suggestion that does not present all the content in the Description in the current form of a long thin cell of a table.

**Additional context**
N/A

**Comment by 123MwanjeMike** [comment]
Was addressed
