### ISSUE TITLE
[locate] Cannot open saved planning space

### ISSUE THREAD

**Issue by danielogen** [airqo-platform/AirQo-frontend#616]
**What were you trying to achieve?**
Accessing previously saved planning space

**What are the expected results?**
A previously saved polygon (planning space) should appear on the map

**What are the received results?**
Error shown in the screenshot attached

**What are the steps to reproduce the issue?**
Go to the location feature and click the `Open` button

**In what environment did you encounter the issue?**
 - OS: macOS Big Sur
 - Versio: Chrome (Brave)

**Additional context**
None 

<img width="1425" alt="Screen Shot 2022-05-11 at 6 05 15 PM" src="https://user-images.githubusercontent.com/15224992/167885548-21026a6b-02db-4998-8124-8a6d3a110b5a.png">

**Comment by HassanBahati** [comment]
@123MwanjeMike what is the expected behavior here?

**Comment by HassanBahati** [comment]
@123MwanjeMike is this issue still persisting?

**Comment by 123MwanjeMike** [comment]
> @123MwanjeMike is this issue still persisting?

Hi @danielogen, please provide some more light on this. cc @Baalmart

**Comment by Baalmart** [comment]
> > @123MwanjeMike is this issue still persisting?
> 
> Hi @danielogen, please provide some more light on this. cc @Baalmart

Hi @123MwanjeMike , thanks for the call out.
I think the best (quickest) way of finding out is by following the instructions in the issue details while using the Locate feature in the platform?
