### ISSUE TITLE
Incorrect success alert on registration page

### ISSUE THREAD

**Issue by Baalmart** [airqo-platform/AirQo-frontend#79]
- What were you trying to achieve?
Correct success alert
- What are the expected results?
alert appears after registration
- What are the received results?
![image](https://user-images.githubusercontent.com/1590213/87310104-28133d00-c526-11ea-850a-80857f82ccbe.png)
- What are the steps to reproduce the issue?
Just visit registration page
- In what environment did you encounter the issue?
web browser, etc...

**Comment by danielogen** [comment]
Hi @Baalmart, this issue doesn't seem to appear in the latest master. You can check it out, might save you some precious time :)

**Comment by ja-odur** [comment]
This has been resolved
