### ISSUE TITLE
Unhandled Rejection (TypeError): Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by Baalmart** [airqo-platform/AirQo-frontend#82]
- What were you trying to achieve?
Login Analytics
- What are the expected results?
Analytics dashboard after successful Login
- What are the received results?
An error message.
![image](https://user-images.githubusercontent.com/1590213/87395818-9f92ac00-c5ba-11ea-81e9-5a015b089ca8.png)

- What are the steps to reproduce the issue?
Ensure that the backend auth-service is NOT running. Then run the following commands:
`cd AirQo-frontend/analytics`
run `npm install`
run `npm run local`
- In what environment did you encounter the issue?
Chrome browser

**Comment by ja-odur** [comment]
THis is outdated. We dont have `analytics` frontend app anymore
