### ISSUE TITLE
Add a back-to-top feature on the AirQo docs

### ISSUE THREAD

**Issue by 123MwanjeMike** [airqo-platform/AirQo-frontend#844]
**Is your feature request related to a problem? Please describe.**
When users are accessing the documentation, users can struggle to scroll back to the start of a given page.

**Describe the solution you'd like**
We would like the users to simply click an icon and they are taken straight to the top of a page without having to manually scroll.

**Additional context**
The [AirQo docs](https://staging-docs.airqo.net/#/) source files can be found [here](https://github.com/airqo-platform/AirQo-frontend/tree/staging/docs)

**Comment by saipranithswargam** [comment]
i would like to work on this issue

**Comment by 123MwanjeMike** [comment]
Great @saipranithswargam.
Feel free to jump in and raise a PR whenever you're ready.

**Comment by HassanBahati** [comment]
@saipranithswargam how it going? any way i could help?

**Comment by saipranithswargam** [comment]
@HassanBahati  i've made a pull request just now.

**Comment by HassanBahati** [comment]
> @HassanBahati i've made a pull request just now.

Okay then @saipranithswargam
