### ISSUE TITLE
Add the Hardware guide to the AirQo docs

### ISSUE THREAD

**Issue by 123MwanjeMike** [airqo-platform/AirQo-frontend#845]
**Describe the solution you'd like**
We would like to add the [AirQo Monitor guide](https://drive.google.com/file/d/1LotNVXHDYedjNEN_V8QQA6bY-i-CAE5-/view?usp=sharing) to the [AirQo docs](https://staging-docs.airqo.net/#/)

**Additional context**
The [AirQo docs](https://staging-docs.airqo.net/#/) source files can be found [here](https://github.com/airqo-platform/AirQo-frontend/tree/staging/docs)

**Comment by HassanBahati** [comment]
@123MwanjeMike is there someone handling this issue?

**Comment by HassanBahati** [comment]
> Not really @HassanBahati. Want to take it up?

Yeah sure

**Comment by 123MwanjeMike** [comment]
Feel free to jump in @HassanBahati
