### ISSUE TITLE
Change the AirQo docs loader message from "Please wait..." to "Loading..."

### ISSUE THREAD

**Issue by 123MwanjeMike** [airqo-platform/AirQo-frontend#846]
**Describe the solution you'd like**
Before the [AirQo docs](https://staging-docs.airqo.net/#/) content loads, a loader screen is presented with a "Please wait..." message. We want to update the message to "Loading..."

**Additional context**
The line of code to change is https://github.com/airqo-platform/AirQo-frontend/blob/d01f8a49fec0c33dfebdcf9f5cf10630c0f2a3a3/docs/index.html#L19

**Comment by sotiriszogos** [comment]
Hello, could you please assign it to me?

**Comment by 123MwanjeMike** [comment]
Right away @sotiriszogos
