### ISSUE TITLE
Convert different sub project directories into git submodules of the project

### ISSUE THREAD

**Issue by 123MwanjeMike** [airqo-platform/AirQo-frontend#847]
**Is your feature request related to a problem? Please describe.**
We have a mono repo for our different products i.e [docs](https://github.com/airqo-platform/AirQo-frontend/tree/staging/docs), [website](https://github.com/airqo-platform/AirQo-frontend/tree/staging/website), [mobile](https://github.com/airqo-platform/AirQo-frontend/tree/staging/mobile), [platform](https://github.com/airqo-platform/AirQo-frontend/tree/staging/platform), and [netmanager](https://github.com/airqo-platform/AirQo-frontend/tree/staging/netmanager). The challenge with this is that the clone of the repo gets too large especially for contributors that are not interested in contributing to all the products. Also, versioning around the different products gets trick when one wants to switch between products 

**Describe the solution you'd like**
We would like the different product folders( [docs](https://github.com/airqo-platform/AirQo-frontend/tree/staging/docs), [website](https://github.com/airqo-platform/AirQo-frontend/tree/staging/website), [mobile](https://github.com/airqo-platform/AirQo-frontend/tree/staging/mobile), [platform](https://github.com/airqo-platform/AirQo-frontend/tree/staging/platform), and [netmanager](https://github.com/airqo-platform/AirQo-frontend/tree/staging/netmanager)) to be converted into Git submodules.

**Additional context**
- [Git Submodules](https://www.git-scm.com/book/en/v2/Git-Tools-Submodules)

**Comment by siddharth595** [comment]
Can you please assign this to me? Thankyou!

**Comment by 123MwanjeMike** [comment]
Sure thing @siddharth595

**Comment by 123MwanjeMike** [comment]
Hi @siddharth595 
We’re closing this issue on account that it may have more implications than earlier observed.
Apologies for the inconvenience this causes.
I hope you can be able to find another issue that interests you.
