### ISSUE TITLE
Add the AirQo docs favicon

### ISSUE THREAD

**Issue by 123MwanjeMike** [airqo-platform/AirQo-frontend#848]
**Describe the solution you'd like**
We would like to add a favicon to the [AirQo docs](https://staging-docs.airqo.net/#/) site that is the same as that used on the [AirQo website](https://airqo.africa/).

**Additional context**
- You can find the favicons in the [this website codebase folder](https://github.com/airqo-platform/AirQo-frontend/tree/master/website/frontend/assets)
- The [docs](https://staging-analytics.airqo.net/) codebase can be found [here](https://github.com/airqo-platform/AirQo-frontend/tree/staging/docs)

**Comment by abhayjeet007** [comment]
I would like to contribute to this. please assign this to me.
