### ISSUE TITLE
Setup automated tests for the docs codebase

### ISSUE THREAD

**Issue by 123MwanjeMike** [airqo-platform/AirQo-frontend#851]
**Describe the solution you'd like**
Currently, we have no automated testing setup on the docs project. We would like to set them up with for the currently existing documentations added.

**Additional context**
- The [docs](https://staging-analytics.airqo.net/) codebase can be found [here](https://github.com/airqo-platform/AirQo-frontend/tree/staging/docs)
- An example test cypress folder can be found [here](https://github.com/airqo-platform/AirQo-frontend/tree/staging/platform/cypress)

**Breakdown**
- [x] #961
- [x] #962
- [x] #963
- [x] #964
- [x] #965
- [x] #966
  - AirQo logo present
  - Buttons funtionality
  - Has the texts "Clean Air for all African Cities"

**Comment by HassanBahati** [comment]
@123MwanjeMike i seek  for more context here...are the tests for any particular sections of the docs or as whole?

**Comment by HassanBahati** [comment]
@123MwanjeMike are there any further resources you would recommend me to look into for reference?

**Comment by 123MwanjeMike** [comment]
> @123MwanjeMike i seek for more context here...are the tests for any particular sections of the docs or as whole?

Hi @HassanBahati 
This may be a little broad.
The tests would include checking that button clicks works, the pages are being rendered, the links are not dead links, check for random text in a page's text.
I will need to break it down into sub issues for easier addressing.

Let me know if you are up for a video chat and we do it together.

**Comment by 123MwanjeMike** [comment]
> @123MwanjeMike are there any further resources you would recommend me to look into for reference?

The best resource is the [Cypress docs](https://docs.cypress.io/guides/overview/why-cypress) I must say.
