### ISSUE TITLE
CORS Error on About Page

### ISSUE THREAD

**Issue by kallyas** [airqo-platform/AirQo-frontend#863]
**What were you trying to achieve?**
I was trying to visit the about page to find more information regarding the project

**What are the expected results?**
About page with some information

**What are the received results?**
![Blank Page](https://user-images.githubusercontent.com/60466044/195928070-4acdf20f-7404-4544-b983-1166218c72ba.png)

Upon inspecting, I found out it was due to cors error that is stopping the page to render since it depends on the api with the endpoints `/teams` and `/partner`

![Error Logs](https://user-images.githubusercontent.com/60466044/195928514-313b315c-dc8a-4fff-bf58-98f2b5603bcd.png)

**What are the steps to reproduce the issue?**
Visit [About us](https://airqo.africa/about-us) page and inspect the page

**In what environment did you encounter the issue?**
 - Windows 10 Edge

**Additional context**
Any other information you would like to share?

**Comment by 123MwanjeMike** [comment]
Thank you for catching and reporting this bug @kallyas.
Let us address and update you on it asap.
