### ISSUE TITLE
Add Calibration guide to AirQo docs

### ISSUE THREAD

**Issue by Codebmk** [airqo-platform/AirQo-frontend#865]
**Describe the solution you'd like**
We would like to add the [AirQo Calibration guide](https://docs.google.com/document/d/1z65wAjDscZvA9i_oLyHaNm7xKjkaq_DFBd3vjapVzXA/edit?usp=sharing) to the [AirQo docs](https://staging-docs.airqo.net/#/)

**Additional context**
The [AirQo docs](https://staging-docs.airqo.net/#/) source files can be found [here](https://github.com/airqo-platform/AirQo-frontend/tree/staging/docs)

**Comment by HassanBahati** [comment]
@Codebmk for more clarity on this issue....should a mackdown file  `/AirQuo/AirQuo-frontend/docs/calibration-guide.md` be created and content [https://docs.google.com/document/d/1z65wAjDscZvA9i_oLyHaNm7xKjkaq_DFBd3vjapVzXA/edit?usp=sharing](https://docs.google.com/document/d/1z65wAjDscZvA9i_oLyHaNm7xKjkaq_DFBd3vjapVzXA/edit?usp=sharing) added ?

**Comment by Codebmk** [comment]
Yes @HassanBahati

**Comment by HassanBahati** [comment]
@Codebmk is the calibration guide side bar item supposed to appear in each of the top level sections (API,Platform,Mobile APP) or it should appear once as the 4th item to API,Platform,Mobile APP 
![Screenshot from 2022-10-17 22-28-48](https://user-images.githubusercontent.com/65954740/196266014-3f47b55b-4619-4a45-8de0-943cb8697179.png)

**Comment by Codebmk** [comment]
@HassanBahati it is appearing right under Platform section as it is part of the Platform

**Comment by HassanBahati** [comment]
> 

Okay then

**Comment by Codebmk** [comment]
@HassanBahati what is the status of your progress with this issue? I will share the images shortly.

**Comment by HassanBahati** [comment]
> @HassanBahati what is the status of your progress with this issue? I will share the images shortly.

@Codebmk i opened a pull request #869
