### ISSUE TITLE
Add favicon to analytics platform

### ISSUE THREAD

**Issue by Codebmk** [airqo-platform/AirQo-frontend#866]
Describe the solution you'd like
We would like to add a favicon to the [Analytics Ptatform](https://staging-analytics.airqo.net/) site similar to the one used on the [AirQo website](https://airqo.africa/).

Additional context

You can find the favicons in the [this website codebase folder](https://github.com/airqo-platform/AirQo-frontend/tree/master/website/frontend/assets)
The platform codebase can be found [here](https://github.com/airqo-platform/AirQo-frontend/tree/staging/platform)

**Comment by bhups1106** [comment]
Hi @Codebmk, I am interested to look into this issue. Would you please assign this to me ?

**Comment by bhanuloshali1995** [comment]
@Codebmk 
Fixed in this PR. Please review
https://github.com/airqo-platform/AirQo-frontend/pull/867

**Comment by 123MwanjeMike** [comment]
Hi @Codebmk, this issue duplicates #849.
