### ISSUE TITLE
Upgrade GitHub workflows from use of `set-output` command which is deprecated 

### ISSUE THREAD

**Issue by 123MwanjeMike** [airqo-platform/AirQo-frontend#885]
**What were you trying to achieve?**
Running any of the repo [workflows](https://github.com/airqo-platform/AirQo-frontend/tree/staging/.github/workflows)

**What are the expected results?**
Workflows are expected to run without `set-output` deprecation warnings

**What are the received results?**
All workflows were running with the `set-output` deprecation warning
![image](https://user-images.githubusercontent.com/41787587/197535428-0b4e93c5-9314-443e-88ec-f4fe167c4dc2.png)

**Additional context**
- An example of a GitHub Action workflow run with is warning is [here](https://github.com/airqo-platform/AirQo-frontend/actions/runs/3298162986)
- [This article](https://hynek.me/til/set-output-deprecation-github-actions/) may be of some assistance in solving this.
- The ideal solution addresses this issue in [all the workflows](https://github.com/airqo-platform/AirQo-frontend/tree/staging/.github/workflows)
- Sample link using the command https://github.com/airqo-platform/AirQo-frontend/blob/1b360766a530cda503c37a7c8f6a35b7bc07e21b/.github/workflows/deploy-frontends-to-staging.yml#L69

**Comment by Vinitvh** [comment]
Hi, @123MwanjeMike, can I work on this?

**Comment by 123MwanjeMike** [comment]
Feel free to jump in @Vinitvh 
I’ve assigned it to you as well.
