### ISSUE TITLE
Upgrade GitHub workflows from use of `save-state` command which is deprecated 

### ISSUE THREAD

**Issue by 123MwanjeMike** [airqo-platform/AirQo-frontend#886]
**What were you trying to achieve?**
Running any of the repo [workflows](https://github.com/airqo-platform/AirQo-frontend/tree/staging/.github/workflows)

**What are the expected results?**
Workflows are expected to run without `save-state` deprecation warnings

**What are the received results?**
Workflows were running with the  `save-state` deprecation warning
![image](https://user-images.githubusercontent.com/41787587/197537861-aab95616-d547-459c-befb-7f967b98c358.png)

**Additional context**
- An example of a GitHub Action workflow run with is warning is [here](https://github.com/airqo-platform/AirQo-frontend/actions/runs/3297947619)
- [This article](https://hynek.me/til/set-output-deprecation-github-actions/) may provide some insights in solving this.
- The ideal solution addresses this issue in [all the workflows](https://github.com/airqo-platform/AirQo-frontend/tree/staging/.github/workflows)
- This issue is related to #885

**Comment by logesr** [comment]
I can work on this

**Comment by 123MwanjeMike** [comment]
Great @logesr 
Feel free to jump in

**Comment by abhishekr700** [comment]
@123MwanjeMike can I work on this ?

**Comment by 123MwanjeMike** [comment]
Hi @abhishekr700, this issue was unfortunately already assigned.
@logesr, can we reassign this issue to @abhishekr700 especially if you haven't started any works on it?

**Comment by 123MwanjeMike** [comment]
@abhishekr700 , could issue #905 be of interest to you?

**Comment by logesr** [comment]
Hi @123MwanjeMike, I will be starting to work on this today. If needed, we can assing this to @abhishekr700. I can take #905

**Comment by 123MwanjeMike** [comment]
> Hi @123MwanjeMike, I will be starting to work on this today. If needed, we can assing this to @abhishekr700. I can take #905

No worries @logesr, @abhishekr700  can confirm if he's still up for it. Also note that #905 has doesn't need an assignee to get a PR raised for it since it's open to however solves it first

**Comment by 123MwanjeMike** [comment]
Fixed by #899
