### ISSUE TITLE
Update repo README with the correct information

### ISSUE THREAD

**Issue by 123MwanjeMike** [airqo-platform/AirQo-frontend#889]
- On line 3, include the "Calibrate App" to the list of comma separated products mentioned
https://github.com/airqo-platform/AirQo-frontend/blob/2cc2c90097a4d86257304942b197790dcb010a7a/README.md?plain=1#L3

- On this line, replace "in and around Kampala City" with "through out Africa"
https://github.com/airqo-platform/AirQo-frontend/blob/2cc2c90097a4d86257304942b197790dcb010a7a/README.md?plain=1#L7

**Comment by vikash485** [comment]
Hey @123MwanjeMike, I would like to work on this. Please assign it to me.

**Comment by imgourav** [comment]
I can do this, Please assign this issue to me @123MwanjeMike

**Comment by 123MwanjeMike** [comment]
Sure thing @imgourav 
Over to you.

**Comment by vikash485** [comment]
Hey @123MwanjeMike, I commented first for this issue, and I even made a pr for the same, Please check

**Comment by 123MwanjeMike** [comment]
Oh, sorry @imgourav.
@vikash485 had already requested for this issue and already has a PR up.
Could you perphaps take up #891 ?
