### ISSUE TITLE
Fix Calibrate App .env.sample mistake and update respective README.md

### ISSUE THREAD

**Issue by 123MwanjeMike** [airqo-platform/AirQo-frontend#891]
https://github.com/airqo-platform/AirQo-frontend/blob/2cc2c90097a4d86257304942b197790dcb010a7a/calibrate/.env.sample#L6
- The value of `REACT_APP_AUTHORIZATION_TOKEN` is meant to be plainly a JWT token without the "JWT" part. Update the [.env.sample](https://github.com/airqo-platform/AirQo-frontend/blob/staging/calibrate/.env.sample) file from `REACT_APP_AUTHORIZATION_TOKEN=JWT ey123abc` to `REACT_APP_AUTHORIZATION_TOKEN=ey123abc`

- The `REACT_APP_AUTHORIZATION_TOKEN` is an [Authentication](https://staging-docs.airqo.net/#/api/?id=authentication) token used to access all API endpoints and so it is always needed. The other task of this issue is to update the [Calibrate App README](https://github.com/airqo-platform/AirQo-frontend/blob/staging/calibrate/README.md) to;
  - Let the users know of the existence of the .env.sample file, from which they can create their personal `.env` file when contributing to the app
  - Add the [documentation link](https://staging-docs.airqo.net/#/../api/users?id=login) for users on how to get an authentication token.

#### Additional context
- The .env.sample details should be included as prerequisite in the README

**Comment by thomasjvu** [comment]
Hi there, can I take on this issue?

**Comment by 123MwanjeMike** [comment]
Feel free to jump in @thomasjvu

**Comment by abhishekr700** [comment]
Hi, please assign this to me @thomasjvu

**Comment by thomasjvu** [comment]
@abhishekr700 I've already submitted a PR for this issue

**Comment by abhishekr700** [comment]
Hmm, I suppose it wasn't linked to this issue. Thank you for letting me know, @thomasjvu
