### ISSUE TITLE
Add a .env.sample for the Netmanager

### ISSUE THREAD

**Issue by 123MwanjeMike** [airqo-platform/AirQo-frontend#893]
**Is your feature request related to a problem? Please describe.**
While setting up the netmanager, it's difficult to know all the environmental variables one would need to run the application 

**Describe the solution you'd like**
- Can we have a `.env.sample` file as a template for the `.env` file at the root of the [netmanager folder](
https://github.com/airqo-platform/AirQo-frontend/tree/staging/netmanager) with a list of environmental variables and dummy values in it.
- Also, can we update the [netmanager README](https://github.com/airqo-platform/AirQo-frontend/blob/staging/netmanager/README.md) to let users know that the `.env.sample` is merely a template they need to fill with actual values when creating their respective local `.env` file.

**Additional context**
- The contents of the `.env.sample` may include:
```
REACT_APP_BASE_URL=https://staging-platform.airqo.net/api/v1/
REACT_APP_BASE_ANALYTICS_URL=
REACT_APP_BASE_AUTH_SERVICE_URL=
REACT_APP_BASE_DATA_MANAGEMENT_URL=
REACT_APP_BASE_DEVICE_MONITORING_URL=
REACT_APP_BASE_DEVICE_REGISTRY_URL= 
REACT_APP_BASE_LOCATE_URL=
REACT_APP_BASE_LOCATION_REGISTRY_URL=
REACT_APP_BASE_PREDICT_URL=
REACT_APP_MAX_CONFIDENCE_INTERVAL=
REACT_APP_CLOUDINARY_NAME=abcdef
REACT_APP_CLOUDINARY_PRESET=abcdef
REACT_APP_MAPBOX_TOKEN=pk.ey123abc
REACT_APP_JIRA_KEY=abcdef
NODE_PATH=src/
PORT=5000
```
- Empty values are not required for the application to run
- [Here](https://github.com/airqo-platform/AirQo-frontend/blob/staging/calibrate/.env.sample) is a `.env.sample` example

**Comment by rohitkori** [comment]
can you please assign it to me?

**Comment by 123MwanjeMike** [comment]
Sure thing @rohitkori
