### ISSUE TITLE
Add a .env.sample for the website

### ISSUE THREAD

**Issue by 123MwanjeMike** [airqo-platform/AirQo-frontend#894]
**Is your feature request related to a problem? Please describe.**
- While setting up the website, it's difficult to know all the environmental variables one would need to run the application with the [current implementation](https://github.com/airqo-platform/AirQo-frontend/tree/staging/website#create-the-envrc-and-env-files).
- Also, with more values being added to the .env files, the size of the README grows.

**Describe the solution you'd like**
- Can we instead have a `.env.sample` file as a template for the `.env` file at the root of the [website folder](
https://github.com/airqo-platform/AirQo-frontend/tree/staging/website) with a list of environmental variables and dummy values in it.
- Also, can we update the website README "[Create the .envrc and .env files](https://github.com/airqo-platform/AirQo-frontend/tree/staging/website#create-the-envrc-and-env-files)" section to remove the .env values from there and let users know that the `.env.sample` is the template they need to fill with actual values when creating their respective local `.env` file.

**Additional context**
- The contents of the `.env.sample` may include:
```
DATABASE_URI=postgresql://username:password@host:5432/database_name
SECRET_KEY=secret_key
CLOUDINARY_NAME=abcdef
CLOUDINARY_KEY=123
CLOUDINARY_SECRET=abcdef
REACT_WEB_STATIC_HOST=https://storage.googleapis.com/name_of_gcp_bucket/
DJANGO_ALLOWED_HOSTS="localhost,127.0.0.1"
GS_BUCKET_NAME=name_of_gcp_bucket
DEBUG=False
REACT_NETMANAGER_BASE_URL=https://staging-platform.airqo.net/api/v1/
REACT_APP_BASE_AIRQLOUDS_URL=
REACT_APP_BASE_NEWSLETTER_URL=
REACT_APP_WEBSITE_BASE_URL=https://127.0.0.1:3000/api/v1/
GOOGLE_APPLICATION_CREDENTIALS=/path/to/credentials/file.json
REACT_APP_AUTHORIZATION_TOKEN=ey123abc
SECURE_SSL_REDIRECT=False
HTTP_X_FORWARDED_PROTO=http
```
- Empty values are not required for the application to run
- [Here](https://github.com/airqo-platform/AirQo-frontend/blob/staging/calibrate/.env.sample) is a `.env.sample` example
- Add the [documentation link](https://staging-docs.airqo.net/#/../api/users?id=login) for users on how to get an authentication token for the `REACT_APP_AUTHORIZATION_TOKEN` variable.

**Comment by its-me-Harsh-Anand** [comment]
Hey! Can you please assign this to me?

Also, in the .env.sample file, I need to add those values which is written in `additional content` of this issue?

**Comment by 123MwanjeMike** [comment]
That’s right @its-me-Harsh-Anand 
Those are the contents of the .env.sample

**Comment by rohitkori** [comment]
can you please assign it to me?

**Comment by rohitkori** [comment]
> Hi @rohitkori , @its-me-Harsh-Anand is already on top of this issue. I have however assigned you a similar issue #893

okk thanks
