### ISSUE TITLE
Updating app dependency packages

### ISSUE THREAD

**Issue by NoahNsimbe** [airqo-platform/AirQo-frontend#901]
**Is your feature request related to a problem? Please describe.**
The app keeps crushing due to a bug in Firebase Crashlytics. [Link to linked firebase issue](https://github.com/firebase/firebase-android-sdk/issues/4223)

**Describe the solution you'd like**
Updating the [pubspec.yaml](https://github.com/airqo-platform/AirQo-frontend/blob/staging/mobile/pubspec.yaml)  file to use the latest stable versions of all dependency packages. 

- [Link to packages repsoritory](https://pub.dev/)
- [Link to specific failing package](https://pub.dev/packages/firebase_analytics)

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by HassanBahati** [comment]
@NoahNsimbe is anyone working on this ?

**Comment by NoahNsimbe** [comment]
@HassanBahati nobody.  You can work on it. Feel free to reachout incase of any blockers.

**Comment by HassanBahati** [comment]
> @NoahNsimbe is anyone working on this ?

okay please
