### ISSUE TITLE
Mobile app unit tests and code coverage

### ISSUE THREAD

**Issue by noahnsimbe** [airqo-platform/AirQo-frontend#903]
**Is your feature request related to a problem? Please describe.**
The mobile app does not have unit tests and code coverage setup.

**Describe the solution you'd like**

- Create tests for the extensions. [Link to extensions](https://github.com/airqo-platform/AirQo-frontend/blob/staging/mobile/lib/utils/extensions.dart)
- Setup code coverage and add badges to the readme file

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by HassanBahati** [comment]
@NoahNsimbe do we have anyone working on this...what is the status of this issue

**Comment by HassanBahati** [comment]
@NoahNsimbe  are there any further resources you would recommend me to look into for reference?

**Comment by HassanBahati** [comment]
> Hi @HassanBahati. Nobody is working on this issue. Below are some resources.
> 
> * [Flutter testing](https://docs.flutter.dev/testing)
> * [Unit testing](https://docs.flutter.dev/cookbook/testing/unit/introduction)
> * [Widget Testing](https://docs.flutter.dev/cookbook/testing/widget/introduction)
> * [Mocking dependencies](https://docs.flutter.dev/cookbook/testing/unit/mocking)
> * [Integration Testing](https://docs.flutter.dev/cookbook/testing/integration/introduction)

thank you! let me take a look through

**Comment by NoahNsimbe** [comment]
Hi @HassanBahati, sorry for the late response. Going to share the environment variables with you. cc @BenjaminSsempala

**Comment by NoahNsimbe** [comment]
Hi @HassanBahati [let's finish cleaning up the environment variables](https://github.com/airqo-platform/AirQo-frontend/pull/992), then share them with you.

**Comment by HassanBahati** [comment]
> Hi @HassanBahati [let's finish cleaning up the environment variables](https://github.com/airqo-platform/AirQo-frontend/pull/992), then share them with you.

HI @NoahNsimbe happy new year! What could be the progress on this?

**Comment by NoahNsimbe** [comment]
Hi @HassanBahati. Happy new year! Apologies for the late reply. 
We updated to [readme](https://github.com/airqo-platform/AirQo-frontend/tree/staging/mobile#for-contributors) with instructions on how a create a .env.dev file.

**Comment by NoahNsimbe** [comment]
Let me know incase you are having any challenges.

**Comment by HassanBahati** [comment]
hi @NoahNsimbe been facing quite of challenges with the setup....please advice on how possible it is to schedule a call with you?

**Comment by NoahNsimbe** [comment]
Hi @HassanBahati, yes it is possible. Let's have a chat using email (noah@airqo.net) .

**Comment by HassanBahati** [comment]
> Hi @HassanBahati, yes it is possible. Let's have a chat using email ([noah@airqo.net](mailto:noah@airqo.net)) .

Okay please, I am going to get in touch shortly
