### ISSUE TITLE
Remove .idea mobile folder from git and GitHub

### ISSUE THREAD

**Issue by NoahNsimbe** [airqo-platform/AirQo-frontend#912]
**Is your feature request related to a problem? Please describe.**
The[ .idea folder](https://github.com/airqo-platform/AirQo-frontend/tree/staging/mobile/.idea) in the [mobile app folder](https://github.com/airqo-platform/AirQo-frontend/tree/staging/mobile) is still tracked by git yet the [.gitignore file](https://github.com/airqo-platform/AirQo-frontend/blob/b9ea64a3ae55a75904e225db31dc19010985888d/mobile/.gitignore#L16) was setup to ignore it.

**Describe the solution you'd like**
Any future modifications to the [.idea folder](https://github.com/airqo-platform/AirQo-frontend/tree/staging/mobile/.idea) on a developer's machine should not be tracked by git.

**Describe alternatives you've considered**
None

**Additional context**
Related PRs
- https://github.com/airqo-platform/AirQo-frontend/pull/911
- The solution simply involves deleting the [.idea](https://github.com/airqo-platform/AirQo-frontend/tree/staging/.idea) at the repo root and [.idea](https://github.com/airqo-platform/AirQo-frontend/tree/staging/mobile/.idea) in the mobile app folder

**Comment by HassanBahati** [comment]
@NoahNsimbe would it also be handy to remove it from the root ? seems like the [idea](https://github.com/airqo-platform/AirQo-frontend/tree/staging/.idea) folder also appears at the root.

**Comment by NoahNsimbe** [comment]
> @NoahNsimbe would it also be handy to remove it from the root ? seems like the [.idea folder](https://github.com/airqo-platform/AirQo-frontend/tree/staging/.idea) also appears at the root.

Yes please. I would be.. Thanks @HassanBahati
