### ISSUE TITLE
Update the CONTRIBUTION guide to let contributors know they don't need to wait to be assigned to an issue

### ISSUE THREAD

**Issue by 123MwanjeMike** [airqo-platform/AirQo-frontend#913]
**Is your feature request related to a problem? Please describe.**
Whenever a new issue is created, contributors usually assume that they need to be assigned the issue to address it. This should not be the case as anyone should be able to address an issue they like and are able to as long as there is there is no PR for it yet.

**Describe the solution you'd like**
We would like to have the contribution guide updated so that contributors are made aware of this before hand.

**Describe alternatives you've considered**
Always adding the comment below to every new issue
> Please note that you don't need to be assigned to this issue to work on it. Simply raise a PR that address it and add Closes #<issue number> in the PR description to [automatically link the your PR to the issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword), or mention the PR in this issue.

This is rather repetitive and undisered

**Additional context**
- [Here](https://github.com/airqo-platform/AirQo-frontend/blob/staging/CONTRIBUTING.md) is the contribution guide
- The line of code to update is:
https://github.com/airqo-platform/AirQo-frontend/blob/4cf986142b319c2ce177949d0752e4c478a104cd/CONTRIBUTING.md?plain=1#L34

- Add the following to that section:
> Note that you don't need to be assigned to this issue to work on it. Simply raise a PR that address it and add Closes #issue-number in the PR description to [automatically link the your PR to the issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword), or mention the PR in this issue

**Comment by HassanBahati** [comment]
@123MwanjeMike is anyone working on this?

**Comment by 123MwanjeMike** [comment]
Not really @HassanBahati
