### ISSUE TITLE
Outdated checkout step version

### ISSUE THREAD

**Issue by 123MwanjeMike** [airqo-platform/AirQo-frontend#942]
**What were you trying to achieve?**
Run a GitHub action step that involves checking out the codebase

**What are the expected results?**
The checkout to run without any errors or warnings.

**What are the received results?**
The checkout step run with the warning as below
![image](https://user-images.githubusercontent.com/41787587/201325891-d4ae12f0-3b2c-4b15-bde5-50a495ecd59d.png)

**What are the steps to reproduce the issue?**
Checkout [this workflow run](https://github.com/airqo-platform/AirQo-frontend/actions/runs/3443565374) and scroll to the bottom

**Additional context**
- This issue is cause by use of an outdated version(v2 instead of v3) of the [actions/checkout](https://github.com/actions/checkout) GitHub app so the solution would simply involve updating this version.
- The ideal solution updates this version in all [these workflow files](https://github.com/airqo-platform/AirQo-frontend/tree/staging/.github/workflows)
- A sample line to update is below
  https://github.com/airqo-platform/AirQo-frontend/blob/b084cca08fdfeffd2f10b8e93b2d008204c8417c/.github/workflows/deploy-k8s-changes-to-staging.yml#L23

**Comment by 123MwanjeMike** [comment]
Sure thing @Vinitvh

**Comment by moses-kisakye** [comment]
@123MwanjeMike anything for a total beginner (python) to jump on?

**Comment by 123MwanjeMike** [comment]
> @123MwanjeMike anything for a total beginner (python) to jump on?

Hi @moses-kisakye 
Let me cross check to see if we can create any.
For now I propose you take a look at #902 
cc @NoahNsimbe @FaithDaka

**Comment by moses-kisakye** [comment]
> > @123MwanjeMike anything for a total beginner (python) to jump on?
> 
> Hi @moses-kisakye Let me cross check to see if we can create any. For now I propose you take a look at #902 cc @NoahNsimbe @FaithDaka

I've checked and seen that the you just commended that its outdated. how can that be
