### ISSUE TITLE
[Netmanager] Missing device details for device with "missing" channels IDs

### ISSUE THREAD

**Issue by Baalmart** [airqo-platform/AirQo-frontend#97]
Works well....requires a review of ports and all when testing locally....

- What were you trying to achieve?
See the device details 
- What are the expected results?
See an appropriate message on device details page for those whose channel ID is missing in the backend
![image](https://user-images.githubusercontent.com/1590213/88336840-5a9b1200-cd3e-11ea-9f19-9c09aaade076.png)

- What are the received results?
Empty graphs after clicking on devices whose channel IDs are non existent....
- What are the steps to reproduce the issue?
check out the Locate Device Registry, click on a device for more information and then check out the information for a device whose channel ID is missing from the backend implementation
- In what environment did you encounter the issue?
Google chrome browser

**Comment by ja-odur** [comment]
outdated
