### ISSUE TITLE
Update old versions of GitHub actions

### ISSUE THREAD

**Issue by 123MwanjeMike** [airqo-platform/AirQo-frontend#990]
**What were you trying to achieve?**
- Run a Github workflow

**What are the expected results?**
- All actions to run without any errors/warnings

**What are the received results?**
- All outdated versions of GitHub apps threw the warnings below
  ![image](https://user-images.githubusercontent.com/41787587/206683740-18234b0d-3a63-4e80-892a-96373a6bb89a.png)
  ![image](https://user-images.githubusercontent.com/41787587/206683599-eb4fb4a6-84d4-4450-9468-d7d73677df69.png)

**What are the steps to reproduce the issue?**
- Re run any previously run GitHub action.
- You should see the warnings after the run
- A sample run with the warning is [here](https://github.com/airqo-platform/AirQo-frontend/actions/runs/3574575786)

**Additional context**
- This is because the currently used versions of the GitHub actions are using [Node12 which is being phased out by GitHub](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
- The GitHub actions to update include
  - [ ] [docker/login-action](https://github.com/docker/login-action) https://github.com/airqo-platform/AirQo-frontend/blob/12bb9a6ec998f0c08b3945b661bfc13dc1f98b16/.github/workflows/deploy-frontends-to-staging.yml#L121
  - [ ] [azure/k8s-set-context](https://github.com/Azure/k8s-set-context) https://github.com/airqo-platform/AirQo-frontend/blob/12bb9a6ec998f0c08b3945b661bfc13dc1f98b16/.github/workflows/deploy-frontends-to-staging.yml#L147
- The ideal solution updates these versions in [all the workflows](https://github.com/airqo-platform/AirQo-frontend/tree/staging/.github/workflows).

**Comment by HassanBahati** [comment]
hi @123MwanjeMike for this particular, would web be moving to `docker/login-action@v2` ? as thats what i see in [docker documentation](https://docs.docker.com/language/java/configure-ci-cd/)
https://github.com/airqo-platform/AirQo-frontend/blob/6754a1b1a376e5f235e340b8fcd4a466b92a6de9/.github/workflows/deploy-frontends-to-staging.yml#L373

**Comment by 123MwanjeMike** [comment]
> hi @123MwanjeMike for this particular, would we be moving to `docker/login-action@v2` ? as thats what i see in [docker documentation](https://docs.docker.com/language/java/configure-ci-cd/)
> 
> https://github.com/airqo-platform/AirQo-frontend/blob/6754a1b1a376e5f235e340b8fcd4a466b92a6de9/.github/workflows/deploy-frontends-to-staging.yml#L373

Exactly. Just like the GitHub action's home page([docker/login-action](https://github.com/docker/login-action)) also specifies
![image](https://user-images.githubusercontent.com/41787587/211314550-d2d07302-4245-4d3d-9aeb-4d4df626f80d.png)

**Comment by HassanBahati** [comment]
> > hi @123MwanjeMike for this particular, would we be moving to `docker/login-action@v2` ? as thats what i see in [docker documentation](https://docs.docker.com/language/java/configure-ci-cd/)
> > https://github.com/airqo-platform/AirQo-frontend/blob/6754a1b1a376e5f235e340b8fcd4a466b92a6de9/.github/workflows/deploy-frontends-to-staging.yml#L373
> 
> Exactly @HassanBahati . Just like the GitHub action's home page([docker/login-action](https://github.com/docker/login-action)) also specifies ![image](https://user-images.githubusercontent.com/41787587/211314550-d2d07302-4245-4d3d-9aeb-4d4df626f80d.png)

This is noted. Thanks @123MwanjeMike . i have already updated a few through #1014 . The pr will be ready tomorrow as in the meantime i will be looking out for others that are out of date.

**Comment by HassanBahati** [comment]
This is noted. Thanks @123MwanjeMike . i have already updated a few through #1014 . The pr will be ready tomorrow as in the meantime i will be looking out for others that are out of date.
